global:
  pattern: multicloud-gitops-amx
  singleArgoCD: true
  secretLoader:
    disabled: true
  options:
    installPlanApproval: Automatic
    syncPolicy: Automatic
    useCSV: false
main:
  variant: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
